// <auto-generated />
using ClassLibrary1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassLibrary1.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    partial class CustomerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassLibrary1.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("CreditRating")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "8 Johnstown Road, Cork",
                            CreditRating = 200f,
                            Name = "Patricia McKenna"
                        },
                        new
                        {
                            ID = 2,
                            Address = "Garden House Crowther Way, Dublin",
                            CreditRating = 400f,
                            Name = "Helen Bennett"
                        },
                        new
                        {
                            ID = 3,
                            Address = "1900 Oak St., Vancouver",
                            CreditRating = 2000f,
                            Name = "Yoshi Tanami"
                        },
                        new
                        {
                            ID = 4,
                            Address = "12 Orchestra Terrace, Dublin 20",
                            CreditRating = 800f,
                            Name = "John Steel"
                        },
                        new
                        {
                            ID = 5,
                            Address = "Rue Joseph-Bens 532, Brussels",
                            CreditRating = 600f,
                            Name = "Catherine Dewey"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
